server:
  port: 20001


spring:
  application:
    name: eureka_client1
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:10001/eureka/




